/**
 * Complete Supabase Database Types
 * Based on the legacy house-of-guess schema
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      matches: {
        Row: {
          id: number;
          round_number: number;
          home_team_id: number;
          home_team_name: string;
          home_team_short_name: string | null;
          home_team_logo: string | null;
          home_team_colors: Json | null;
          away_team_id: number;
          away_team_name: string;
          away_team_short_name: string | null;
          away_team_logo: string | null;
          away_team_colors: Json | null;
          slug: string;
          start_time: string;
          start_timestamp: number;
          status: string;
          status_code: number;
          status_description: string | null;
          home_score: number;
          away_score: number;
          live_score_home: number | null;
          live_score_away: number | null;
          live_score_minute: number | null;
          live_score_period: string | null;
          tournament_id: number;
          tournament_name: string;
          tournament_slug: string | null;
          league_id: number | null;
          league_name: string | null;
          league_country: string | null;
          cached: boolean;
          last_updated: string;
          source: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: number;
          round_number: number;
          home_team_id: number;
          home_team_name: string;
          home_team_short_name?: string | null;
          home_team_logo?: string | null;
          home_team_colors?: Json | null;
          away_team_id: number;
          away_team_name: string;
          away_team_short_name?: string | null;
          away_team_logo?: string | null;
          away_team_colors?: Json | null;
          slug: string;
          start_time: string;
          start_timestamp: number;
          status: string;
          status_code: number;
          status_description?: string | null;
          home_score?: number;
          away_score?: number;
          live_score_home?: number | null;
          live_score_away?: number | null;
          live_score_minute?: number | null;
          live_score_period?: string | null;
          tournament_id: number;
          tournament_name: string;
          tournament_slug?: string | null;
          league_id?: number | null;
          league_name?: string | null;
          league_country?: string | null;
          cached?: boolean;
          last_updated?: string;
          source?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: number;
          round_number?: number;
          home_team_id?: number;
          home_team_name?: string;
          home_team_short_name?: string | null;
          home_team_logo?: string | null;
          home_team_colors?: Json | null;
          away_team_id?: number;
          away_team_name?: string;
          away_team_short_name?: string | null;
          away_team_logo?: string | null;
          away_team_colors?: Json | null;
          slug?: string;
          start_time?: string;
          start_timestamp?: number;
          status?: string;
          status_code?: number;
          status_description?: string | null;
          home_score?: number;
          away_score?: number;
          live_score_home?: number | null;
          live_score_away?: number | null;
          live_score_minute?: number | null;
          live_score_period?: string | null;
          tournament_id?: number;
          tournament_name?: string;
          tournament_slug?: string | null;
          league_id?: number | null;
          league_name?: string | null;
          league_country?: string | null;
          cached?: boolean;
          last_updated?: string;
          source?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      predictions: {
        Row: {
          id: string;
          user_id: string;
          match_id: number;
          home_team_goals: number;
          away_team_goals: number;
          winner_team: string;
          predicted_at: string;
          updated_at: string;
          locked: boolean | null;
          prediction_set_id: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          match_id: number;
          home_team_goals: number;
          away_team_goals: number;
          winner_team: string;
          predicted_at?: string;
          updated_at?: string;
          locked?: boolean | null;
          prediction_set_id?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          match_id?: number;
          home_team_goals?: number;
          away_team_goals?: number;
          winner_team?: string;
          predicted_at?: string;
          updated_at?: string;
          locked?: boolean | null;
          prediction_set_id?: string | null;
        };
        Relationships: [];
      };
      users_profiles: {
        Row: {
          id: string;
          firebase_id: string;
          name: string;
          email: string | null;
          role: string | null;
          points: number | null;
          predictions_count: number | null;
          xp: number | null;
          level: number | null;
          favorite_team_id: number | null;
          favorite_team_name: string | null;
          favorite_team_logo: string | null;
          avatar: string | null;
          notifications_enabled: boolean | null;
          public_profile: boolean | null;
          pending_payments: number | null;
          total_approved_payments: number | null;
          approved_count: number | null;
          pending_count: number | null;
          created_at: string | null;
          updated_at: string | null;
        };
        Insert: {
          id: string;
          firebase_id: string;
          name: string;
          email?: string | null;
          role?: string | null;
          points?: number | null;
          predictions_count?: number | null;
          xp?: number | null;
          level?: number | null;
          favorite_team_id?: number | null;
          favorite_team_name?: string | null;
          favorite_team_logo?: string | null;
          avatar?: string | null;
          notifications_enabled?: boolean | null;
          public_profile?: boolean | null;
          pending_payments?: number | null;
          total_approved_payments?: number | null;
          approved_count?: number | null;
          pending_count?: number | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          firebase_id?: string;
          name?: string;
          email?: string | null;
          role?: string | null;
          points?: number | null;
          predictions_count?: number | null;
          xp?: number | null;
          level?: number | null;
          favorite_team_id?: number | null;
          favorite_team_name?: string | null;
          favorite_team_logo?: string | null;
          avatar?: string | null;
          notifications_enabled?: boolean | null;
          public_profile?: boolean | null;
          pending_payments?: number | null;
          total_approved_payments?: number | null;
          approved_count?: number | null;
          pending_count?: number | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Relationships: [];
      };
      current_round: {
        Row: {
          id: string;
          round_number: number;
          name: string;
          start_date: string | null;
          end_date: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          round_number: number;
          name: string;
          start_date?: string | null;
          end_date?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          round_number?: number;
          name?: string;
          start_date?: string | null;
          end_date?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      teams: {
        Row: {
          id: number;
          sofascore_id: string | null;
          name: string;
          short_name: string | null;
          name_code: string | null;
          slug: string | null;
          logo_url: string | null;
          country_name: string | null;
          country_alpha2: string | null;
          country_alpha3: string | null;
          tournament_id: number | null;
          tournament_name: string | null;
          created_at: string;
          updated_at: string;
          last_sync_at: string | null;
        };
        Insert: {
          id: number;
          sofascore_id?: string | null;
          name: string;
          short_name?: string | null;
          name_code?: string | null;
          slug?: string | null;
          logo_url?: string | null;
          country_name?: string | null;
          country_alpha2?: string | null;
          country_alpha3?: string | null;
          tournament_id?: number | null;
          tournament_name?: string | null;
          created_at?: string;
          updated_at?: string;
          last_sync_at?: string | null;
        };
        Update: {
          id?: number;
          sofascore_id?: string | null;
          name?: string;
          short_name?: string | null;
          name_code?: string | null;
          slug?: string | null;
          logo_url?: string | null;
          country_name?: string | null;
          country_alpha2?: string | null;
          country_alpha3?: string | null;
          tournament_id?: number | null;
          tournament_name?: string | null;
          created_at?: string;
          updated_at?: string;
          last_sync_at?: string | null;
        };
        Relationships: [];
      };
      user_tournament_points: {
        Row: {
          id: string;
          user_id: string;
          tournament_id: number;
          points: number;
          predictions_count: number;
          exact_scores: number;
          correct_results: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          tournament_id: number;
          points?: number;
          predictions_count?: number;
          exact_scores?: number;
          correct_results?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          tournament_id?: number;
          points?: number;
          predictions_count?: number;
          exact_scores?: number;
          correct_results?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      prize_pool: {
        Row: {
          id: number;
          total: number;
          total_pending: number;
          total_approved: number;
          participants: number;
          currency: string;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: number;
          total?: number;
          total_pending?: number;
          total_approved?: number;
          participants?: number;
          currency?: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: number;
          total?: number;
          total_pending?: number;
          total_approved?: number;
          participants?: number;
          currency?: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      tournaments: {
        Row: {
          id: number;
          name: string;
          slug: string | null;
          short_name: string | null;
          logo_url: string | null;
          wallpaper_url: string | null;
          country: string | null;
          format: string | null;
          has_rounds: boolean | null;
          has_groups: boolean | null;
          has_playoff_series: boolean | null;
          status: string | null;
          is_featured: boolean | null;
          display_order: number | null;
          most_titles_team_id: number | null;
          most_titles_team_name: string | null;
          most_titles_count: number | null;
          current_phase: string | null;
          season_id: number | null;
          last_champions: Json | null;
          start_date: string | null;
          end_date: string | null;
          created_at: string | null;
          updated_at: string | null;
          last_sync_at: string | null;
        };
        Insert: {
          id: number;
          name: string;
          slug?: string | null;
          short_name?: string | null;
          logo_url?: string | null;
          wallpaper_url?: string | null;
          country?: string | null;
          format?: string | null;
          has_rounds?: boolean | null;
          has_groups?: boolean | null;
          has_playoff_series?: boolean | null;
          status?: string | null;
          is_featured?: boolean | null;
          display_order?: number | null;
          most_titles_team_id?: number | null;
          most_titles_team_name?: string | null;
          most_titles_count?: number | null;
          current_phase?: string | null;
          season_id?: number | null;
          last_champions?: Json | null;
          start_date?: string | null;
          end_date?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
          last_sync_at?: string | null;
        };
        Update: {
          id?: number;
          name?: string;
          slug?: string | null;
          short_name?: string | null;
          logo_url?: string | null;
          wallpaper_url?: string | null;
          country?: string | null;
          format?: string | null;
          has_rounds?: boolean | null;
          has_groups?: boolean | null;
          has_playoff_series?: boolean | null;
          status?: string | null;
          is_featured?: boolean | null;
          display_order?: number | null;
          most_titles_team_id?: number | null;
          most_titles_team_name?: string | null;
          most_titles_count?: number | null;
          current_phase?: string | null;
          season_id?: number | null;
          last_champions?: Json | null;
          start_date?: string | null;
          end_date?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
          last_sync_at?: string | null;
        };
        Relationships: [];
      };
      tournament_seasons: {
        Row: {
          id: number;
          tournament_id: number;
          name: string;
          year: string | null;
          is_current: boolean | null;
          current_round_type: string | null;
          current_round_number: number | null;
          start_date: string | null;
          end_date: string | null;
          created_at: string | null;
          updated_at: string | null;
        };
        Insert: {
          id: number;
          tournament_id: number;
          name: string;
          year?: string | null;
          is_current?: boolean | null;
          current_round_type?: string | null;
          current_round_number?: number | null;
          start_date?: string | null;
          end_date?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Update: {
          id?: number;
          tournament_id?: number;
          name?: string;
          year?: string | null;
          is_current?: boolean | null;
          current_round_type?: string | null;
          current_round_number?: number | null;
          start_date?: string | null;
          end_date?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Relationships: [];
      };
      payments: {
        Row: {
          id: string;
          user_id: string;
          amount: number;
          status: string;
          pix_key: string;
          transaction_id: string | null;
          request_date: string;
          admin_id: string | null;
          admin_name: string | null;
          processed_at: string | null;
          rejection_reason: string | null;
          user_name: string;
          user_team: string | null;
          user_logo: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          amount: number;
          status?: string;
          pix_key: string;
          transaction_id?: string | null;
          request_date?: string;
          admin_id?: string | null;
          admin_name?: string | null;
          processed_at?: string | null;
          rejection_reason?: string | null;
          user_name: string;
          user_team?: string | null;
          user_logo?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          amount?: number;
          status?: string;
          pix_key?: string;
          transaction_id?: string | null;
          request_date?: string;
          admin_id?: string | null;
          admin_name?: string | null;
          processed_at?: string | null;
          rejection_reason?: string | null;
          user_name?: string;
          user_team?: string | null;
          user_logo?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      deposits: {
        Row: {
          id: string;
          user_id: string;
          amount: number;
          status: string;
          payment_method: string;
          pix_data: Json | null;
          created_at: string;
          confirmed_at: string | null;
          cancelled_at: string | null;
          notes: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          amount: number;
          status?: string;
          payment_method?: string;
          pix_data?: Json | null;
          created_at?: string;
          confirmed_at?: string | null;
          cancelled_at?: string | null;
          notes?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          amount?: number;
          status?: string;
          payment_method?: string;
          pix_data?: Json | null;
          created_at?: string;
          confirmed_at?: string | null;
          cancelled_at?: string | null;
          notes?: string | null;
        };
        Relationships: [];
      };
      players: {
        Row: {
          id: number;
          sofascore_id: string | null;
          name: string;
          first_name: string | null;
          last_name: string | null;
          short_name: string | null;
          slug: string | null;
          team_id: number | null;
          jersey_number: string | null;
          shirt_number: number | null;
          position: string | null;
          positions_detailed: string[] | null;
          height: number | null;
          preferred_foot: string | null;
          date_of_birth: string | null;
          date_of_birth_timestamp: number | null;
          gender: string | null;
          deceased: boolean | null;
          country_name: string | null;
          country_alpha2: string | null;
          country_alpha3: string | null;
          contract_until_timestamp: number | null;
          proposed_market_value: number | null;
          proposed_market_value_currency: string | null;
          user_count: number | null;
          created_at: string | null;
          updated_at: string | null;
          last_sync_at: string | null;
        };
        Insert: {
          id: number;
          sofascore_id?: string | null;
          name: string;
          first_name?: string | null;
          last_name?: string | null;
          short_name?: string | null;
          slug?: string | null;
          team_id?: number | null;
          jersey_number?: string | null;
          shirt_number?: number | null;
          position?: string | null;
          positions_detailed?: string[] | null;
          height?: number | null;
          preferred_foot?: string | null;
          date_of_birth?: string | null;
          date_of_birth_timestamp?: number | null;
          gender?: string | null;
          deceased?: boolean | null;
          country_name?: string | null;
          country_alpha2?: string | null;
          country_alpha3?: string | null;
          contract_until_timestamp?: number | null;
          proposed_market_value?: number | null;
          proposed_market_value_currency?: string | null;
          user_count?: number | null;
          created_at?: string | null;
          updated_at?: string | null;
          last_sync_at?: string | null;
        };
        Update: {
          id?: number;
          sofascore_id?: string | null;
          name?: string;
          first_name?: string | null;
          last_name?: string | null;
          short_name?: string | null;
          slug?: string | null;
          team_id?: number | null;
          jersey_number?: string | null;
          shirt_number?: number | null;
          position?: string | null;
          positions_detailed?: string[] | null;
          height?: number | null;
          preferred_foot?: string | null;
          date_of_birth?: string | null;
          date_of_birth_timestamp?: number | null;
          gender?: string | null;
          deceased?: boolean | null;
          country_name?: string | null;
          country_alpha2?: string | null;
          country_alpha3?: string | null;
          contract_until_timestamp?: number | null;
          proposed_market_value?: number | null;
          proposed_market_value_currency?: string | null;
          user_count?: number | null;
          created_at?: string | null;
          updated_at?: string | null;
          last_sync_at?: string | null;
        };
        Relationships: [];
      };
      notifications: {
        Row: {
          id: string;
          user_id: string;
          type: string;
          title: string;
          message: string;
          data: Json | null;
          read: boolean | null;
          created_at: string | null;
          read_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          type: string;
          title: string;
          message: string;
          data?: Json | null;
          read?: boolean | null;
          created_at?: string | null;
          read_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          type?: string;
          title?: string;
          message?: string;
          data?: Json | null;
          read?: boolean | null;
          created_at?: string | null;
          read_at?: string | null;
        };
        Relationships: [];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
  };
}

// Utility types for easier access
export type UserProfile = Database["public"]["Tables"]["users_profiles"]["Row"];
export type Match = Database["public"]["Tables"]["matches"]["Row"];
export type Prediction = Database["public"]["Tables"]["predictions"]["Row"];
export type Team = Database["public"]["Tables"]["teams"]["Row"];
export type CurrentRound = Database["public"]["Tables"]["current_round"]["Row"];
export type UserTournamentPoints = Database["public"]["Tables"]["user_tournament_points"]["Row"];
export type PrizePool = Database["public"]["Tables"]["prize_pool"]["Row"];
export type Tournament = Database["public"]["Tables"]["tournaments"]["Row"];
export type TournamentSeason = Database["public"]["Tables"]["tournament_seasons"]["Row"];
export type Payment = Database["public"]["Tables"]["payments"]["Row"];
export type Deposit = Database["public"]["Tables"]["deposits"]["Row"];
export type Player = Database["public"]["Tables"]["players"]["Row"];
export type Notification = Database["public"]["Tables"]["notifications"]["Row"];

// Helper type for user role
export type UserRole = "user" | "admin";
