const teamLogoMap: Record<string, string> = {
  "Atlético Mineiro": "atletico-mg",
  "Atlético-MG": "atletico-mg",
  "Atletico Mineiro": "atletico-mg",
  "Athletico Paranaense": "athletico",
  "Athletico-PR": "athletico",
  "Bahia": "bahia",
  "Botafogo": "botafogo",
  "Ceará": "ceara",
  "Ceara": "ceara",
  "Chapecoense": "chapecoense",
  "Corinthians": "corinthians",
  "Coritiba": "coritiba",
  "Cruzeiro": "cruzeiro",
  "Flamengo": "flamengo",
  "Fluminense": "fluminense",
  "Fortaleza": "fortaleza",
  "Grêmio": "gremio",
  "Gremio": "gremio",
  "Internacional": "internacional",
  "Juventude": "juventude",
  "Mirassol": "mirassol",
  "Palmeiras": "palmeiras",
  "Red Bull Bragantino": "bragantino",
  "Bragantino": "bragantino",
  "Santos": "santos",
  "São Paulo": "saopaulo",
  "Sao Paulo": "saopaulo",
  "Sport Recife": "sport",
  "Sport": "sport",
  "Vasco da Gama": "vasco",
  "Vasco": "vasco",
  "Vitória": "vitoria",
  "Vitoria": "vitoria",

  "América Mineiro": "america-mg",
  "América-MG": "america-mg",
  "Atlético Goianiense": "atletico-go",
  "Atlético-GO": "atletico-go",
  "Avaí": "avai",
  "Goiás": "goias",
  "Guarani": "guarani",
  "Ponte Preta": "ponte-preta",
  "Cuiabá": "cuiaba",
  "Paysandu SC": "paysandu",
  "Paysandu": "paysandu",
  "Vila Nova FC": "vila-nova",
  "Vila Nova": "vila-nova",
  "Londrina": "londrina",
  "Figueirense": "figueirense",
  "Joinville": "joinville",
  "Santa Cruz": "santa-cruz",
  "Grêmio Novorizontino": "novorizontino",
  "Novorizontino": "novorizontino",
  "São Bernardo": "sao-bernardo",
  "Tombense": "tombense",
  "Operário-PR": "operario-pr",
  "Operário": "operario-pr",
  "CRB": "crb",
  "CSA": "csa",
  "ABC": "abc",
  "Remo": "remo",
  "Nova Iguaçu": "nova-iguacu",
  "Volta Redonda": "volta-redonda",
  "Portuguesa": "portuguesa",
  "Madureira": "madureira",
  "Amazonas FC": "amazonas",
  "Amazonas": "amazonas",
  "Manaus": "manaus",

  "River Plate": "river",
  "Boca Juniors": "boca-juniors",
  "Peñarol": "penarol",
  "Nacional": "nacional",
  "Libertad": "libertad",
  "Cerro Porteño": "cerro-porteno",
  "Guaraní": "guarani-py",
  "LDU": "ldu",
  "Barcelona SC Guayaquil": "barcelona-sc",
  "Barcelona SC": "barcelona-sc",
  "Independiente del Valle": "independiente-del-valle",
  "Universidad Católica": "universidad-catolica",
  "Coquimbo Unido": "coquimbo",
  "O'Higgins": "ohiggins",
  "Huachipato": "huachipato",
  "Bolívar": "bolivar",
  "The Strongest": "the-strongest",
  "Club Always Ready": "always-ready",
  "Nacional Potosí": "nacional-potosi",
  "Independiente Santa Fe": "santa-fe",
  "Independiente Medellín": "independiente-medellin",
  "Junior Barranquilla": "junior",
  "Deportes Tolima": "tolima",
  "Deportivo Táchira": "deportivo-tachira",
  "Deportivo La Guaira": "la-guaira",
  "Carabobo FC": "carabobo",
  "Universidad Central": "universidad-central",
  "Alianza Lima": "alianza-lima",
  "Universitario de Deportes": "universitario",
  "Club Sporting Cristal": "sporting-cristal",
  "Cusco FC": "cusco",
  "Estudiantes de La Plata": "estudiantes",
  "Rosario Central": "rosario-central",
  "CA Lanús": "lanus",
  "Argentinos Juniors": "argentinos-juniors",
  "Independiente Rivadavia": "independiente-rivadavia",
  "Platense": "platense",
  "Juventud de Las Piedras": "juventud",
  "Liverpool UY": "liverpool-uy",
  "CS 2 de Mayo": "2-de-mayo",
};

export function getTeamLogoPath(teamName: string): string {
  if (!teamName) return "/images/logo/waiting.svg";

  const mapped = teamLogoMap[teamName];
  if (mapped) return `/images/logo/${mapped}.svg`;

  const slug = teamName
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/\s+/g, "-");
  return `/images/logo/${slug}.svg`;
}

export function getTeamLogoById(teamId: number | string): string {
  return `/api/team-logo/${teamId}`;
}
